import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from '@/components/Footer'

const fontPoppins = Poppins({
  subsets: ["latin"],
  weight: ["400","500","600","700"]
});

export const metadata: Metadata = {
  title: "Niaga Jaya Electronic",
  description: "Generated by Project2",
  icons:{
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontPoppins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="container mx-auto px-4">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
